### ISSUE TITLE
some additions - playing internet streams / Stereoboom, August, PlayLink also work

### ISSUE THREAD

**Issue by iisquazar** [AndersFluur/IEastMediaRoom#1]
The Stereoboommm MR200 and MR300, August media players, Venz 501A and Müzo/PlayLink Cubblestone can also be controlled via this script.

To play internet streams:
http://IP-AudioCast/httpapi.asp?command=setPlayerCmd:play:http://pr320.pinguinradio.nl/listen.pls
(http://pr320.pinguinradio.nl/listen.pls is an example url)

To play songs from a NAS:
http://IP-AudioCast/httpapi.asp?command=setPlayerCmd:play:http://IP-Synology/fichier.mp3

Hope this is a good addition to the text?

**Comment by AndersFluur** [comment]
Thanks. Updated with devices and example
