### ISSUE TITLE
command to hide SSID

### ISSUE THREAD

**Issue by DaBozzz** [AndersFluur/IEastMediaRoom#4]
The command to set the SSID of the WiFi network of a LinkPlay device to hidden is _/httpapi.asp?command=setHideSSID:1_

Tested on an August WR320.

**Comment by baldram** [comment]
Maybe you could create a Pull Request? 
It's like I did here: https://github.com/AndersFluur/IEastMediaRoom/pulls?q=is%3Apr+is%3Aclosed and it was merged later on.

**Comment by AndersFluur** [comment]
Commited suggested change
